"""Core datatypes for the scenario template engine.

The unit of measurement is a *scenario template*: a tiny declarative spec of
what to probe, expanded by the engine into a concrete battery of `tools/call`
requests against a live server's actual schemas. Every axis is a 0..100 score
derived deterministically from the recorded exchanges, so results reproduce
across machines and runs.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

GRADES = ["A", "B", "C", "D", "F"]

MODES = ["required", "all", "missing", "wrong-type", "oversize", "empty"]
PHASES = ["baseline", "stale", "drifted"]


@dataclass
class DriftSpec:
    """A mid-run schema mutation to apply via the server's control method."""
    tool: str
    add_required: List[str] = field(default_factory=list)


@dataclass
class Template:
    """A scenario template: an intent, not a concrete battery."""
    name: str
    description: str = ""
    select: str = "*"                      # "*" | "a,b" | "regex:..."
    mode: str = "required"                 # see MODES
    expect: str = "ok"                     # expected outcome for well-formed calls
    drift: Optional[DriftSpec] = None


@dataclass
class CallSpec:
    """One concrete tools/call generated by expansion."""
    seq: int
    tool: str
    arguments: Dict[str, Any]
    expect: str                            # "ok" | "invalid"
    phase: str                             # "baseline" | "stale" | "drifted"
    source: str = ""                       # which schema field generated it


@dataclass
class CallRecord:
    """The outcome of one generated call, classified by the scorer."""
    spec: CallSpec
    ok: bool
    outcome: str                           # "ok" | "invalid" | "other-error" | "eof" | "timeout"
    message: str = ""
    tokens: int = 0


@dataclass
class ServerResult:
    """One template battery executed against one server."""
    template: str
    server: str
    scores: Dict[str, float]
    grade: str
    calls_total: int = 0
    ok_calls: int = 0
    invalid_calls: int = 0
    drift_seen: bool = False               # server honored mutation + list_changed
    drifted_schema: Dict[str, Any] = field(default_factory=dict)
    records: List[CallRecord] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)


@dataclass
class BattReport:
    """Full battery output ready for rendering or export."""
    results: List[ServerResult]
    generated_at: str = ""
    template: str = ""

    def score(self, template: str) -> Optional[ServerResult]:
        for r in self.results:
            if r.template == template:
                return r
        return None

    @property
    def best_grade(self) -> str:
        for g in GRADES:
            if any(r.grade == g for r in self.results):
                return g
        return "F"

    @property
    def servers(self) -> List[str]:
        seen: List[str] = []
        for r in self.results:
            if r.server not in seen:
                seen.append(r.server)
        return seen


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def grade_for(score: float) -> str:
    if score >= 90:
        return "A"
    if score >= 75:
        return "B"
    if score >= 55:
        return "C"
    if score >= 35:
        return "D"
    return "F"


def select_tools(tools: List[Dict[str, Any]], selector: str) -> List[Dict[str, Any]]:
    """Apply a template's tool selector to a live tools/list."""
    if selector in ("*", "all"):
        return list(tools)
    if selector.startswith("regex:"):
        pattern = selector[len("regex:"):]
        rx = re.compile(pattern)
        return [t for t in tools if rx.search(t.get("name", ""))]
    wanted = {s.strip() for s in selector.split(",") if s.strip()}
    return [t for t in tools if t.get("name") in wanted]
